name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      # Stap 1: Gebruik GitHub Secrets om een .env-bestand aan te maken.
      - name: Create .env file from secrets
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          # Voeg hier meer secrets toe indien nodig

      # Stap 2: Start de applicatie op de achtergrond.
      - name: Start app
        run: npm start &

      # Stap 3: Wacht op de applicatie om volledig te starten.
      - name: Wait for app to be ready
        run: sleep 10

      # Stap 4: Voer de Cypress-tests uit.
      - name: Run Cypress tests
        run: npx cypress run
